project:
  type: website
  render:
    - "*.qmd"

bibliography: refs.bib

website:
  title: "SDS 355: Fall 2025"
  navbar:
    left:
      - text: "Home"
        icon: house
        href: index.qmd
      - icon: chevron-contract
        href: syllabus.qmd
      - icon: calendar
        href: schedule.qmd
      - text: "Assignments"
        icon: list-task
        menu:
          - icon: speedometer
            href: hw.qmd
          - icon: code-slash
            href: sporcle.qmd
          - icon: file-arrow-up
            href: colloquium.qmd
          - icon: file-pdf
            href: paper.qmd
    right:
      - icon: slack
        href: https://sds-355-01-202601.slack.com/
  page-footer: 
    left: "Created by Ben Baumer" 


format:
  html:
    theme: journal
    highlight: textmate
    toc: true
    toc-depth: 6
    css: smith.css
