---
title: "Colloquium presentation"
bibliography: refs.bib
# use citeproc
citeproc: true
csl: apa-cv.csl
suppress-bibliography: true
---

In a [colloquium](https://en.wikipedia.org/wiki/Colloquium), there is usually a different speaker each week. 
During the second half of the semester, our class will run as a quasi-colloquium, wherein you will take turns presenting a sports analytics paper to the rest of the class. 
This seminar is very common in graduate school, and is a great way to learn how to read a research paper at a deep level. 

Your presentation should take about half of the class period (i.e., 35-40 minutes). 
Your goal is maximize each other student's understanding of the paper by the time they leave the room. 

Here is some advice and ground rules:

- You can expect that the rest of the class will have read the paper. 
- You can use slides but you don't have to. You can ask the author for any slides that they may have already made and use those. 
- You can use your own code or code from another source. 
- Don't just lecture---prepare some type of activity (lasting no more than ~10-15 minutes) that will engage the other students and help them understand the material. 


## Expectations

You will choose a partner, and a [paper](#suggested-papers), and a date during the [second half of the semester](schedule.qmd), and send them to me for approval. 
If I approve, we will put you on the schedule and post the paper to the rest of the class. 
If I do not approve, try again. 
By **Wednesday, October 8th** we will have the colloquium schedule and topics set. 

- If you choose to work alone, you will present **one paper**
- If you choose to work with a partner, you will present **two papers**

# Suggested papers

You are free to present any paper on any topic in sports analytics, provided that:

- it is published in a peer-reviewed journal
- it's not one of the other papers we are reading for this class
- it is approved by me

Good places to look for papers:

- [*Journal of Quantitative Analysis in Sports*](https://www.degruyterbrill.com/journal/key/jqas/html)
- [*Journal of Sports Analytics*](https://journals.sagepub.com/home/san)
- [Previous NESSISs](https://nessis.org/nessis23.html)
- [Google Scholar](https://scholar.google.com/)
- See relevant sections and references in:  
  @baumer2023big
- Anything by previous [Statistics in Sports Significant Contributors](https://community.amstat.org/sis/aboutus/honorees)

The following is a **non-exhaustive** list of high-quality papers which I think would be appropriate. 

## Baseball

1. @lindsey1963investigation
1. @Albert2015
1. @elmore2022bang
1. @baumer2015openwar
1. @yan2025comparing
1. @jensen2009hierarchical
1. @sidle2018using
1. @bouzarth2021swing
1. @deshpande2017hierarchical

## Basketball

1. @Deshpande2016
1. @cervone2016multiresolution
1. @franks2015characterizing
1. @terner2021modeling
1. @lopez2015building

## Football

1. @Yurko2019nflwar
1. @nguyen2024here
1. @brill2025analytics
1. @dutta2020unsupervised
1. @mallepalle2020extracting
1. @yurko2020going
1. @Yam2019
1. @martin2018markov
1. @DeshpandeEvans2020
1. @urschel2011
1. @White2002
1. @glickman2017estimating
1. @ChuReyersThomsonWu2020
1. @Lock2014
1. @Reyers2021quarterback

## Hockey

1. @thomas2013competing
1. @brian2011regression
1. @beaudoin2010strategies

## Tennis

1. @kovalchik2019calibration
1. @kovalchik2016searching

## Multisport

1. @macdonald2020recreating
1. @franks2016metaanalytics
1. @Bradley1952
1. @Lopez2018

## Other

1. @de2025age
1. @maymin2021smart
1. @Elo1978

