---
title: "Research"
subtitle: "SDS 355"
author: "Prof. Baumer" 
date: "2025-10-27"
format: 
  revealjs:
    slide-number: true
    footer: "SDS 355"
    logo: "https://github.com/SmithCollege-SDS/sds/raw/master/man/figures/logo.png"
    theme: solarized
execute: 
  echo: true
  message: false
  warning: false
---

## Statistics in Sports Significant Contributor Award

::: footer
<https://community.amstat.org/sis/aboutus/honorees>
:::

```{r}
library(tidyverse)
library(scholar)
```

```{r}
#| eval: false
sigs <- read_csv(here::here("data/sig_contributors.csv")) |>
  mutate(papers = map(scholar_id, get_publications)) 
sigs

papers <- sigs |>
  unnest(cols = papers) |>
  rename(paper_title = title)

write_rds(papers, here::here("data/papers.rda"))
```

```{r}
#| include: false
papers <- read_rds(here::here("data/papers.rda"))
```

## Most cited sportsball papers

```{r}
papers |>
  filter(str_detect(paper_title, "sports|ball|home run|winning")) |>
  select(year, scholar, cites, paper_title) |>
  arrange(desc(cites)) |>
  print(n = 21)
```

## Most cited "baseball" papers

```{r}
papers |>
  filter(grepl("baseball", paper_title)) |>
  select(year, scholar, cites, paper_title) |>
  arrange(desc(cites))
```

## Venues

```{r}
papers |>
  filter(grepl("sports|ball|home run", paper_title)) |>
  group_by(journal) |>
  summarize(
    N = n(), 
    avg_cites = mean(cites), 
    med_cites = median(cites)
  ) |>
  arrange(desc(N)) |>
  knitr::kable(digits = 1)
```
